name: 'Content Test'
description: 'Runs to test zerobias-org content packages'
inputs:
  run-integration-tests:
    description: 'Set to true to run the integrationTest.sh script'
    required: false
    default: 'true'
  test-timeout:
    description: 'Timeout in seconds for test commands'
    required: false
    default: '300'

runs:
  using: "composite"
  steps:
    - name: Restore git cache
      uses: actions/cache@v4
      with:
        path: .git
        key: ${{ github.repository }}-git-folder

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.head_ref }}

    - name: Setup node
      uses: zerobias-org/devops/nx-actions/setup-node@main

    - name: Install sem
      shell: bash
      run: |
        if ! command -v sem-apply &> /dev/null
        then
          gem install schema-evolution-manager
        fi

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.117.0'
        extended: true

    - name: Install nx
      shell: bash
      run: |
        npm install -g nx@22.4.2
      env:
        NPM_TOKEN: ${{ env.READ_TOKEN }}
        ZB_TOKEN: ${{ env.ZB_TOKEN }}

    - name: Install dependencies
      shell: bash
      run: |
        cp .npmrc $HOME/.npmrc
        npm ci
        npm install -g @zerobias-org/devops-tools@latest
      env:
        NPM_TOKEN: ${{ env.READ_TOKEN }}
        ZB_TOKEN: ${{ env.ZB_TOKEN }}

    - name: Detect changed packages
      id: detect_changes
      shell: bash
      run: |
        # Detect packages with actual source changes (ignoring lock files)
        CHANGED_DIRS=$(npx detect-changes origin/main)
        if [ -z "$CHANGED_DIRS" ]; then
          echo "No packages changed, skipping build"
          echo "HAS_CHANGES=false" >> $GITHUB_OUTPUT
        else
          echo "Changed packages:"
          echo "$CHANGED_DIRS"
          # Convert newlines to spaces for safe use in for loops
          CHANGED_DIRS_INLINE=$(echo "$CHANGED_DIRS" | tr '\n' ' ')
          echo "CHANGED_DIRS=$CHANGED_DIRS_INLINE" >> $GITHUB_OUTPUT
          echo "HAS_CHANGES=true" >> $GITHUB_OUTPUT
        fi
      env:
        NPM_TOKEN: ${{ env.READ_TOKEN }}
        ZB_TOKEN: ${{ env.ZB_TOKEN }}

    - name: Build changed packages
      if: steps.detect_changes.outputs.HAS_CHANGES == 'true'
      shell: bash
      run: |
        echo "${{ steps.detect_changes.outputs.CHANGED_DIRS }}" | tr ' ' '\n' | \
        xargs -P4 -I{} bash -c '
          pkg="{}"
          if [ -f "$pkg/package.json" ]; then
            PROJECT_NAME=$(jq -r ".name" "$pkg/package.json")
            # Check if nx:build script exists in package.json
            if jq -e ".scripts[\"nx:build\"]" "$pkg/package.json" > /dev/null 2>&1; then
              echo "Building $PROJECT_NAME (from $pkg)"
              timeout 300 nx nx:build "$PROJECT_NAME" || echo "Warning: build failed for $PROJECT_NAME"
            else
              echo "Skipping $PROJECT_NAME - no nx:build target"
            fi
          fi
        '
      env:
        NPM_TOKEN: ${{ env.READ_TOKEN }}
        ZB_TOKEN: ${{ env.ZB_TOKEN }}
        JAVA_OPTS: "-Xms256m -Xmx1024m"

    # Need at at least a file in there as download action will fail if no artifact found
    # upload does not upload empty folders
    - name: create github actions upload folder
      shell: bash
      run: |
        mkdir ci-upload
        echo "Upload your artifacts to this location for debugging or sharing accross jobs" > ci-upload/README.md
      
    - name: test:integration
      if: inputs.run-integration-tests == 'true'
      shell: bash
      run: |
        bash ${{ github.action_path }}/integrationTest.sh
      env:
        NPM_TOKEN: ${{ env.READ_TOKEN }}
        DYNAMO_DB_TABLE: ${{ env.AWS_DYNAMO_DB_TABLE }}
        AWS_ACCESS_KEY_ID: ${{ env.AWS_DYNAMO_DB_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ env.AWS_DYNAMO_DB_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ env.AWS_DYNAMO_DB_REGION }}
        AWS_ENDPOINT: ${{ env.AWS_DYNAMO_DB_ENDPOINT }}
        EVENT_SOURCE: Memory
        SCHEDULER_SOURCE: Memory

    - name: test:prepublish:init
      if: steps.detect_changes.outputs.HAS_CHANGES == 'true'
      shell: bash
      run: |
        npx prepublish-init
      env:
        NPM_TOKEN: ${{ env.READ_TOKEN }}

    - name: test:prepublish
      if: steps.detect_changes.outputs.HAS_CHANGES == 'true'
      shell: bash
      run: |
        npm i -g @zerobias-com/platform-dataloader@latest
        # Then check per-package scripts
        echo "${{ steps.detect_changes.outputs.CHANGED_DIRS }}" | tr ' ' '\n' | \
        xargs -P4 -I{} bash -c '
          pkg="{}"
          if [ -f "$pkg/package.json" ]; then
            echo "Running prepublishtest for $pkg"
            (cd "$pkg" && timeout ${{ inputs.test-timeout }} npx prepublishtest)
          fi
        '
      env:
        NPM_TOKEN: ${{ env.READ_TOKEN }}
        DYNAMO_DB_TABLE: ${{ env.AWS_DYNAMO_DB_TABLE }}
        AWS_ACCESS_KEY_ID: ${{ env.AWS_DYNAMO_DB_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ env.AWS_DYNAMO_DB_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ env.AWS_DYNAMO_DB_REGION }}
        AWS_ENDPOINT: ${{ env.AWS_DYNAMO_DB_ENDPOINT }}
        EVENT_SOURCE: Memory
        SCHEDULER_SOURCE: Memory

    - name: test:postpublish
      shell: bash
      run: |
        if [ -x scripts/postpublish.sh ]
        then
          bash scripts/postpublish.sh --dry-run
        fi
      env:
        NPM_TOKEN: ${{ env.READ_TOKEN }}
        UPLOAD_FOLDER_NAME: ci-upload

    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ci-upload
        path: ci-upload/
        if-no-files-found: warn
        retention-days: 1

    - name: Slack Notification on failure
      uses: slackapi/slack-github-action@v2.1.1
      if: failure() && env.SLACK_DEVOPS_NOTIFICATIONS != ''
      with:
        webhook: ${{ env.SLACK_DEVOPS_NOTIFICATIONS }}
        webhook-type: incoming-webhook
        payload: |
          text: "${{ github.repository }} PR Test Failed"
          attachments:
            - color: "#ff0000"
              fallback: "PR Test Failed"
              title: ":fire: ${{ github.repository }} PR Test Failed"
              text: "Workflow run failed"
              footer: "<https://github.com/${{ github.repository }}|${{ github.repository }}> • <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View run>"
              mrkdwn_in:
                - text
                - footer
