name: 'Content Pre-Release'
description: 'Handle the pre-release flow for zerobias-org content'
inputs:
  since:
    description: 'The ref to compare to determine what has released'
    required: false
    default: 'origin/main'
runs:
  using: 'composite'
  steps:
    - name: check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'

    - name: bootstrap
      shell: bash
      run: |
        npm ci
      env:
        NPM_TOKEN: ${{ env.READ_TOKEN }}

    - name: Set dist-tags
      uses: zerobias-org/devops/actions/content-dist-tag@main
      with:
        since: ${{ inputs.since }}

    # Run only if just a tag workflow not a publish
    - name: Post Pre Release
      shell: bash
      run: |
        if [ -x scripts/postprerelease.sh ]
        then
          bash scripts/postprerelease.sh
        fi

    - name: Release Announcement
      uses: zerobias-org/devops/actions/release-announcement@main
      with:
        since: ${{ inputs.since }}
