name: 'Content Publish'
description: 'Runs to publish a zerobias-org content'
inputs:
  publishToken:
    description: Token with permissions to publish packages
    required: true
  update-all:
    description: 'Set to true to update all content in the repo'
    required: false
    default: 'false'
  skip-publish-announcement:
    description: 'Skips release announcement'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: check out code
      uses: actions/cache@v4
      with:
        path: .git
        key: ${{ github.repository }}-git-folder

    - name: check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: zerobias-org/devops/nx-actions/setup-node@main

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.110.0'
        extended: true

    - name: CDN Update
      uses: zerobias-org/devops/nx-actions/cdn-update@main
      with:
        update-all: ${{ inputs.update-all }}

    - name: configure git user
      shell: bash
      run: |
        git config --global user.email "ci@neverfail.com"
        git config --global user.name "@$GITHUB_ACTOR"

    - name: configure aws tools creds
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ env.AWS_PUBLISHING_ROLE }}
        role-session-name: ${{ github.event.repository.name }}
        aws-region: ${{ env.AWS_PUBLISHING_REGION }}

    - name: save tools profile
      shell: bash
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile tools
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile tools
        aws configure set aws_session_token $AWS_SESSION_TOKEN --profile tools

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        platforms: linux/amd64,linux/arm64

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Install nx
      shell: bash
      run: |
        npm install -g nx@20.5.0
      env:
        NPM_TOKEN: ${{ env.READ_TOKEN }}
        ZB_TOKEN: ${{ env.ZB_TOKEN }}

    - name: Install dependencies
      shell: bash
      run: |
        cp .npmrc $HOME/.npmrc
        npm ci
      env:
        NPM_TOKEN: ${{ env.READ_TOKEN }}
        ZB_TOKEN: ${{ env.ZB_TOKEN }}

    - name: Detect changed packages
      id: detect_changes
      shell: bash
      run: |
        # Get last published tag
        LAST_PUBLISH_TAG=$(git describe --tags --abbrev=0 --match="*" 2>/dev/null || echo "HEAD~1")
        echo "Using base ref: $LAST_PUBLISH_TAG"

        # Detect packages with actual source changes (ignoring lock files)
        CHANGED_DIRS=$(npx detect-changes "$LAST_PUBLISH_TAG")
        if [ -z "$CHANGED_DIRS" ]; then
          echo "No packages changed, skipping build/publish"
          echo "HAS_CHANGES=false" >> $GITHUB_OUTPUT
        else
          echo "Changed packages:"
          echo "$CHANGED_DIRS"
          echo "CHANGED_DIRS<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED_DIRS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "HAS_CHANGES=true" >> $GITHUB_OUTPUT
          echo "BASE_REF=$LAST_PUBLISH_TAG" >> $GITHUB_OUTPUT
        fi
      env:
        NPM_TOKEN: ${{ env.READ_TOKEN }}
        ZB_TOKEN: ${{ env.ZB_TOKEN }}

    - name: Build changed packages
      if: steps.detect_changes.outputs.HAS_CHANGES == 'true'
      shell: bash
      run: |
        for pkg in ${{ steps.detect_changes.outputs.CHANGED_DIRS }}; do
          echo "Building $pkg"
          (cd "$pkg" && npm run build)
        done
      env:
        NPM_TOKEN: ${{ env.READ_TOKEN }}
        ZB_TOKEN: ${{ env.ZB_TOKEN }}
        JAVA_OPTS: "-Xms256m -Xmx1024m"

    - name: prepublish:init
      if: steps.detect_changes.outputs.HAS_CHANGES == 'true'
      shell: bash
      run: |
        for pkg in ${{ steps.detect_changes.outputs.CHANGED_DIRS }}; do
          if [ -f "$pkg/package.json" ] && grep -q '"prepublish-init"' "$pkg/package.json"; then
            echo "Running prepublish-init for $pkg"
            (cd "$pkg" && npm run prepublish-init)
          fi
        done
      env:
        NPM_TOKEN: ${{ env.READ_TOKEN }}
        ZB_TOKEN: ${{ env.ZB_TOKEN }}

    - name: prepublish
      if: steps.detect_changes.outputs.HAS_CHANGES == 'true'
      shell: bash
      run: |
        for pkg in ${{ steps.detect_changes.outputs.CHANGED_DIRS }}; do
          if [ -f "$pkg/package.json" ] && grep -q '"prepublishtest"' "$pkg/package.json"; then
            echo "Running prepublishtest for $pkg"
            (cd "$pkg" && npm run prepublishtest)
          fi
        done
      env:
        NPM_TOKEN: ${{ env.READ_TOKEN }}
        ZB_TOKEN: ${{ env.ZB_TOKEN }}
        DYNAMO_DB_TABLE: ${{ env.AWS_DYNAMO_DB_TABLE }}
        AWS_ACCESS_KEY_ID: ${{ env.AWS_DYNAMO_DB_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ env.AWS_DYNAMO_DB_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ env.AWS_DYNAMO_DB_REGION }}
        AWS_ENDPOINT: ${{ env.AWS_DYNAMO_DB_ENDPOINT }}
        EVENT_SOURCE: Memory
        SCHEDULER_SOURCE: Memory

    - name: publish
      if: steps.detect_changes.outputs.HAS_CHANGES == 'true'
      shell: bash
      env:
        NPM_TOKEN: ${{ inputs.publishToken }}
        ZB_TOKEN: ${{ env.ZB_TOKEN }}
        READ_TOKEN: ${{ env.READ_TOKEN }}
      run: |
        echo `git status`

        # Get changed package names for scoped lerna operations
        CHANGED_NAMES=$(npx get-changed-package-names "${{ steps.detect_changes.outputs.BASE_REF }}" | tr '\n' ',' | sed 's/,$//')
        if [ -z "$CHANGED_NAMES" ]; then
          echo "No package names found, skipping publish"
          echo "HAS_VERSION_CHANGES=false" >> $GITHUB_ENV
          exit 0
        fi
        echo "Publishing packages: $CHANGED_NAMES"

        # Initialize empty packages file
        echo "[]" > /tmp/published-packages.json

        if npm run | grep -q "nx:publish"; then
          echo "had nx:publish running those"
          npx lerna version --scope "{$CHANGED_NAMES}" --no-git-tag-version --no-push --conventional-commits --conventional-graduate --yes

          # Check if lerna version made any changes to package.json files
          if git diff --name-only | grep -q 'package.json'; then
            echo "Version changes detected, capturing packages"
            npx lerna changed --json > /tmp/published-packages.json
            echo "PUBLISHED_PACKAGES_FILE=/tmp/published-packages.json" >> $GITHUB_ENV
            echo "HAS_VERSION_CHANGES=true" >> $GITHUB_ENV
          else
            echo "No version changes detected, skipping notifications"
            echo "HAS_VERSION_CHANGES=false" >> $GITHUB_ENV
          fi
          npm run nx:publish
        else
          npx lerna publish --scope "{$CHANGED_NAMES}" --conventional-commits --conventional-graduate --yes

          # Check if lerna publish made any changes
          if git diff --name-only | grep -q 'package.json'; then
            echo "Publish made changes, capturing packages"
            npx lerna changed --json > /tmp/published-packages.json
            echo "PUBLISHED_PACKAGES_FILE=/tmp/published-packages.json" >> $GITHUB_ENV
            echo "HAS_VERSION_CHANGES=true" >> $GITHUB_ENV
          else
            echo "No changes from publish"
            echo "HAS_VERSION_CHANGES=false" >> $GITHUB_ENV
          fi
        fi

        echo "packages published"

    - name: Commit version changes
      if: env.HAS_VERSION_CHANGES == 'true'
      uses: EndBug/add-and-commit@v9
      with:
        add: '.'
        message: 'chore(release): bump version'
        default_author: github_actions
        push: true

    - name: Update dist tags
      shell: bash
      env:
        NPM_TOKEN: ${{ inputs.publishToken }}
        ZB_TOKEN: ${{ env.ZB_TOKEN }}
      run: |
        PACKAGES=$(npx lerna list --since HEAD~1 --ndjson | jq -c)
        for package in $(echo $PACKAGES | jq -r -c '.location'); do
          NAME=$(cat $package/package.json | jq -r '.name')
          VERSION=$(cat $package/package.json | jq -r '.version') 
          npm dist-tag add $NAME@$VERSION dev
          npm dist-tag add $NAME@$VERSION qa
          npm dist-tag add $NAME@$VERSION uat
          npm dist-tag add $NAME@$VERSION rc
        done

        echo "dist tags updated"

    - name: post publish
      shell: bash
      env:
        NPM_TOKEN: ${{ inputs.publishToken }}
        ZB_TOKEN: ${{ env.ZB_TOKEN }}
        READ_TOKEN: ${{ env.READ_TOKEN }}
        PUBLISHED_PACKAGES_FILE: ${{ env.PUBLISHED_PACKAGES_FILE }}
      run: |
        if [ -x scripts/postpublish.sh ]; then
          scripts/postpublish.sh
        fi

    - name: Release Announcement
      if: ${{ inputs.skip-publish-announcement != 'true' }}
      uses: zerobias-org/devops/nx-actions/release-announcement@main
      with:
        packages-file: ${{ env.PUBLISHED_PACKAGES_FILE }}
