name: 'Content PR Approved'
description: 'Runs when a content pr is labelled approved and does not have a `dev` label.'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Add dev label
      if: '!github.event.pull_request.draft'
      run: gh pr edit --add-label "dev"  || echo "dev label already assigned"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ env.PR_TOKEN }}
