name: 'Image Publish Action'
description: 'Publish an Auditmation image to both ghcr and ecr'
inputs:
  image-name:
    description: 'Name of the image to publish'
    required: true
  image-version:
    description: 'Version of the image to publish'
    required: true
  context-dir:
    description: 'Folder containing the Dockerfile'
    required: true
  build-args:
    description: 'List of build args for the Dockerfile'
    required: false
    default: ''
  image-secrets:
    description: 'List of secrets to mount during build (format: id=secret_name,env=ENV_VAR)'
    required: false
    default: ''
  github-token: 
    description: 'GitHub token to use'
    required: true
  overwrite: 
    description: 'Overwrite the existing image'
    required: false
    default: 'false'
  public:
    description: 'Publish to the public ecr repository'
    required: false
    default: 'false'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: Import Secrets
      uses: hashicorp/vault-action@v3.4.0
      with:
        method: jwt
        url: ${{ secrets.VAULT_ADDR }}
        path: gh-actions
        role: publishing-role
        secrets: |
          operations-kv/data/ci/slack releasesWebhook | SLACK_RELEASES_WEBHOOK ;
          operations-kv/data/ci/slack devopsNotifications | SLACK_DEVOPS_NOTIFICATIONS ;
          operations-kv/data/ci/github username | USERNAME ;
          operations-kv/data/ci/github writePackagesToken | WRITE_TOKEN ;

    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64

    - name: set up docker buildx
      uses: docker/setup-buildx-action@v3
      with:
        buildkitd-flags: --debug

    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ env.USERNAME }}
        password: ${{ env.WRITE_TOKEN }}

    - name: configure aws tools creds
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::961260934100:role/github-actions-publishing-role
        role-session-name: ${{ github.event.repository.name }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Create Repository
      shell: bash
      run: |
        aws ecr create-repository \
          --repository-name ${{ inputs.image-name }} \
          --image-scanning-configuration scanOnPush=true \
          || echo "Already created"
        aws ecr set-repository-policy --repository-name ${{ inputs.image-name }} \
          --policy-text '{ "Version": "2012-10-17", "Statement": [ { "Sid": "ReadonlyAccess", "Effect": "Allow", "Principal": { "AWS": "*" }, "Action": [ "ecr:BatchCheckLayerAvailability", "ecr:BatchGetImage", "ecr:DescribeImageScanFindings", "ecr:DescribeImages", "ecr:DescribeRepositories", "ecr:GetAuthorizationToken", "ecr:GetDownloadUrlForLayer", "ecr:GetRepositoryPolicy", "ecr:ListImages" ], "Condition": { "StringLike": { "aws:PrincipalOrgID": "o-dppyp34ws8" } } } ] }'

    - name: Publish image to GitHub
      uses: docker/build-push-action@v3
      with:
        context: ${{ inputs.context-dir }}
        file: ${{ inputs.context-dir }}/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        build-args: ${{ inputs.build-args }}
        secrets: ${{ inputs.image-secrets }}
        tags: |
          ghcr.io/zerobias-org/${{ inputs.image-name }}:latest
          ghcr.io/zerobias-org/${{ inputs.image-name }}:${{ inputs.image-version }}

    - name: publish image to ECR
      uses: docker/build-push-action@v3
      with:
        context: ${{ inputs.context-dir }}
        file: ${{ inputs.context-dir }}/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        build-args: ${{ inputs.build-args }}
        secrets: ${{ inputs.image-secrets }}
        tags: |
          961260934100.dkr.ecr.us-east-1.amazonaws.com/${{ inputs.image-name }}:latest
          961260934100.dkr.ecr.us-east-1.amazonaws.com/${{ inputs.image-name }}:${{ inputs.image-version }}

    - name: Slack Notification
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_COLOR: good
        SLACK_WEBHOOK: ${{ env.SLACK_RELEASES_WEBHOOK }}
        SLACK_ICON_EMOJI: ':robot:'
        MSG_MINIMAL: 'true'
        SLACK_TITLE: ':gear: new ${{ inputs.image-name }} image published :tada:'
        SLACK_MESSAGE: '${{ inputs.image-name }}:${{ inputs.image-version }}'
        SLACK_FOOTER: ''

    - name: Slack Notification
      uses: rtCamp/action-slack-notify@master
      if: failure()
      env:
        SLACK_WEBHOOK: ${{ env.SLACK_DEVOPS_NOTIFICATIONS }} 
        SLACK_ICON_EMOJI: ":fire"
        MSG_MINIMAL: 'true'
        SLACK_TITLE: ":fire: ${{ inputs.image-name }} image build failed"
        SLACK_MESSAGE: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        SLACK_COLOR: danger
