name: 'Deploy to S3'
description: 'Builds and deploys a JavaScript app to an S3 bucket'
inputs:
  app-name:
    description: 'Name of the application directory'
    required: true
  s3-bucket:
    description: 'Target S3 bucket name'
    required: true
  aws-region:
    description: 'AWS region'
    required: true
  role-to-assume:
    description: 'ARN of the AWS IAM role to assume via OIDC'
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'

    - name: Install dependencies
      run: npm ci
      working-directory: ${{ inputs.app-name }}

    - name: Build application
      run: npm run build
      working-directory: ${{ inputs.app-name }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ${{ inputs.aws-region }}

    - name: Sync to S3
      run: |
        aws s3 sync ${{ inputs.app-name }}/dist s3://${{ inputs.s3-bucket }}/${{ inputs.app-name }} --delete
