name: 'Release Announcement'
description: 'Publish a release announcement to slack and the event router'
inputs:
  since:
    description: 'Ref to compare to for determining releases'
    required: false
    default: 'HEAD~1'
  aws-role-arn:
    description: 'AWS role ARN for publishing release events'
    required: false
    default: 'arn:aws:iam::961260934100:role/github-actions-publishing-role'
  publish-release-event:
    description: 'Whether to publish release event to AWS Lambda'
    required: false
    default: 'true'
  packages-file:
    description: 'Path to JSON file containing published packages (optional, uses lerna list --since if not provided)'
    required: false
    default: ''
  branch:
    description: 'Branch name for environment context (e.g., dev, qa, main)'
    required: false
    default: ''
  dist-tag:
    description: 'NPM dist-tag applied (e.g., rc, dev, qa, latest)'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Generate Slack Message
      id: generateSlackMessage
      shell: bash
      run: |
        output=$(${{ github.action_path }}/bin/generate_slack_message.sh)
        if [ "$output" = "No packages published" ] || [ -z "$output" ]; then
          echo "has_packages=false" >> $GITHUB_OUTPUT
        else
          echo "has_packages=true" >> $GITHUB_OUTPUT
          # Escape for JSON: replace newlines with \n
          escaped=$(echo "$output" | jq -Rs '.')
          # Remove surrounding quotes added by jq
          escaped="${escaped:1:-1}"
          echo "output=${escaped}" >> $GITHUB_OUTPUT
        fi
      env:
        SINCE: ${{ inputs.since }}
        NPM_TOKEN: ${{ env.READ_TOKEN }}
        READ_TOKEN: ${{ env.READ_TOKEN }}
        PACKAGES_FILE: ${{ inputs.packages-file }}

    - name: Slack Notification
      uses: slackapi/slack-github-action@v2.1.1
      if: success() && steps.generateSlackMessage.outputs.has_packages == 'true'
      with:
        webhook: ${{ env.SLACK_RELEASES_WEBHOOK }}
        webhook-type: incoming-webhook
        payload: |
          text: "New ${{ github.repository }} Published"
          attachments:
            - color: "#36a64f"
              fallback: "New Packages Published"
              title: ":robot: New Packages Published :tada:${{ inputs.branch && format(' ({0})', inputs.branch) || '' }}${{ inputs.dist-tag && format(' [tag: {0}]', inputs.dist-tag) || '' }}"
              text: "${{ steps.generateSlackMessage.outputs.output }}"
              footer: "<https://github.com/${{ github.repository }}|${{ github.repository }}> • <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View run>"
              mrkdwn_in:
                - text
                - footer

    - name: Get current PR
      if: inputs.publish-release-event == 'true' && steps.generateSlackMessage.outputs.has_packages == 'true'
      uses: 8BitJonny/gh-get-current-pr@2.1.3
      id: pr

    - name: Configure AWS credentials
      if: inputs.publish-release-event == 'true' && steps.generateSlackMessage.outputs.has_packages == 'true'
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ inputs.aws-role-arn }}
        role-session-name: ${{ github.event.repository.name }}
        aws-region: us-east-1

    - name: Extract package directories
      id: extract_dirs
      if: inputs.publish-release-event == 'true' && steps.generateSlackMessage.outputs.has_packages == 'true'
      shell: bash
      run: |
        if [ -n "${{ inputs.packages-file }}" ] && [ -f "${{ inputs.packages-file }}" ]; then
          # Extract locations from packages file (format: [{name, version, location}])
          PACKAGE_DIRS=$(jq -c '[ .[] | .location ]' "${{ inputs.packages-file }}")
          echo "PACKAGE_DIRS=$PACKAGE_DIRS" >> $GITHUB_OUTPUT
        else
          echo "PACKAGE_DIRS=[]" >> $GITHUB_OUTPUT
        fi

    - name: Publish Release Event
      if: inputs.publish-release-event == 'true' && steps.generateSlackMessage.outputs.has_packages == 'true' && steps.extract_dirs.outputs.PACKAGE_DIRS != '[]'
      uses: zerobias-org/devops/nx-actions/publish-release-event@main
      env:
        PR_ID: ${{ steps.pr.outputs.number }}
        PR_URL: ${{ steps.pr.outputs.pr_url }}
        PR_LABELS: ${{ steps.pr.outputs.pr_labels }}
        PACKAGE_DIRS: ${{ steps.extract_dirs.outputs.PACKAGE_DIRS }}
        NPM_TOKEN: ${{ env.READ_TOKEN }}

    - name: Slack Notification on failure
      uses: slackapi/slack-github-action@v2.1.1
      if: failure() && env.SLACK_DEVOPS_NOTIFICATIONS != ''
      with:
        webhook: ${{ env.SLACK_DEVOPS_NOTIFICATIONS }}
        webhook-type: incoming-webhook
        payload: |
          blocks:
            - type: "section"
              text:
                type: "mrkdwn"
                text: ":fire: ${{ github.repository }} Release Announcement Failed"
            - type: "section"
              text:
                type: "mrkdwn"
                text: "<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View workflow run>"