name: 'Release Announcement'
description: 'Publish a release announcement to slack and the event router'
inputs:
  since:
    description: 'Ref to compare to for determining releases'
    required: false
    default: 'HEAD~1'
  aws-role-arn:
    description: 'AWS role ARN for publishing release events'
    required: false
    default: 'arn:aws:iam::961260934100:role/github-actions-publishing-role'
  publish-release-event:
    description: 'Whether to publish release event to AWS Lambda'
    required: false
    default: 'true'
  packages-file:
    description: 'Path to JSON file containing published packages (optional, uses lerna list --since if not provided)'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Generate Slack Message
      id: generateSlackMessage
      shell: bash
      run: |
        output=$(${{ github.action_path }}/bin/generate_slack_message.sh)
        if [ "$output" = "No packages published" ] || [ -z "$output" ]; then
          echo "has_packages=false" >> $GITHUB_OUTPUT
        else
          echo "has_packages=true" >> $GITHUB_OUTPUT
          # Escape for JSON: replace newlines with \n
          escaped=$(echo "$output" | jq -Rs '.')
          # Remove surrounding quotes added by jq
          escaped="${escaped:1:-1}"
          echo "output=${escaped}" >> $GITHUB_OUTPUT
        fi
      env:
        SINCE: ${{ inputs.since }}
        NPM_TOKEN: ${{ env.READ_TOKEN }}
        READ_TOKEN: ${{ env.READ_TOKEN }}
        PACKAGES_FILE: ${{ inputs.packages-file }}

    - name: Slack Notification
      uses: slackapi/slack-github-action@v2.1.1
      if: success() && steps.generateSlackMessage.outputs.has_packages == 'true'
      with:
        webhook: ${{ env.SLACK_RELEASES_WEBHOOK }}
        webhook-type: incoming-webhook
        payload: |
          text: "New ${{ github.repository }} Published"
          attachments:
            - color: "#36a64f"
              fallback: "New Packages Published"
              title: ":robot: New Packages Published :tada:"
              text: "${{ steps.generateSlackMessage.outputs.output }}"
              footer: "<https://github.com/${{ github.repository }}|${{ github.repository }}> • <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View run>"
              mrkdwn_in:
                - text
                - footer

    - name: Slack Notification on failure
      uses: slackapi/slack-github-action@v2.1.1
      if: failure() && env.SLACK_DEVOPS_NOTIFICATIONS != ''
      with:
        webhook: ${{ env.SLACK_DEVOPS_NOTIFICATIONS }}
        webhook-type: incoming-webhook
        payload: |
          blocks:
            - type: "section"
              text:
                type: "mrkdwn"
                text: ":fire: ${{ github.repository }} Release Announcement Failed"
            - type: "section"
              text:
                type: "mrkdwn"
                text: "<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View workflow run>"