name: 'Setup NodeJS'
description: 'Setup nodejs for zerobias-org use'
inputs:
  nodeVersionFile:
    description: 'NodeJS version file to use'
    required: false
    default: '.nvmrc'
runs:
  using: 'composite'
  steps:
    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
