name: 'CDN Update'
description: 'Publish new or updated files to the cdn'
inputs:
  update-all:
    description: 'Set to true to update all content in the repo'
    required: false
    default: 'false'
  cdn-bucket:
    description: 'S3 bucket to upload to'
    required: false
    default: 'auditmation-cdn'
  changed-dirs:
    description: 'Space-separated list of changed package directories (optional, will detect if not provided)'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::961260934100:role/github-actions-publishing-role
        role-session-name: ${{ github.event.repository.name }}
        aws-region: us-east-1

    - name: save tools profile
      shell: bash
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile tools
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile tools
        aws configure set aws_session_token $AWS_SESSION_TOKEN --profile tools

    - name: Update logos
      shell: bash
      run: |
        if [ "$UPDATE_ALL" == "true" ]; then
          echo "Updating all cdn content"
          # Find all packages with package.json
          PACKAGE_DIRS=$(find packages package -maxdepth 4 -name "package.json" -exec dirname {} \; 2>/dev/null | sort -u)
        elif [ -n "$CHANGED_DIRS_INPUT" ]; then
          echo "Using provided changed directories"
          PACKAGE_DIRS="$CHANGED_DIRS_INPUT"
        else
          echo "Detecting changed cdn content"
          # Get last published tag as base ref
          LAST_PUBLISH_TAG=$(git describe --tags --abbrev=0 --match="*" 2>/dev/null || echo "HEAD~1")
          PACKAGE_DIRS=$(npx detect-changes "$LAST_PUBLISH_TAG" 2>/dev/null || echo "")
        fi

        if [ -z "$PACKAGE_DIRS" ]; then
          echo "No packages to update"
          exit 0
        fi

        # Update logos for each package
        for pkg in $PACKAGE_DIRS; do
          logo=""
          if [ -f "$pkg/logo.svg" ]; then
            logo="$pkg/logo.svg"
          elif [ -f "$pkg/logo.png" ]; then
            logo="$pkg/logo.png"
          fi

          if [ "$logo" != "" ] && [ -f "$pkg/index.yml" ]; then
            echo "Updating $pkg logo"
            filename=$(echo $logo | sed 's/^.*package\///')
            filename=$(echo $filename | sed 's/\/logo\./\./')
            filename=$(echo $filename | sed 's/\//-/g')
            echo "Uploading $logo"
            aws s3 cp $logo s3://$CDN_BUCKET/logos/$filename
            echo "Setting logo url"
            logourl="https://cdn.auditmation.io/logos/$filename" yq -i '.logo = env(logourl)' $pkg/index.yml
          fi
        done
      env:
        UPDATE_ALL: ${{ inputs.update-all }}
        CDN_BUCKET: ${{ inputs.cdn-bucket }}
        CHANGED_DIRS_INPUT: ${{ inputs.changed-dirs }}

    - uses: EndBug/add-and-commit@v9
      with:
        add: .
        author_name: Marvin the Paranoid Android
        author_email: ci@zerobias.com
        message: 'chore: cdn update'
