name: 'Content Test'
description: 'Runs to test zerobias-org content packages'
inputs:
  run-integration-tests:
    description: 'Set to true to run the integrationTest.sh script'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: check out code
      uses: actions/cache@v4
      with:
        path: .git
        key: ${{ github.repository }}-git-folder

    - name: check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.head_ref }}

    - uses: zerobias-org/devops/actions/setup-node@main

    - name: install tooling
      shell: bash
      run: |
        if ! command -v sem-apply &> /dev/null
        then
          gem install schema-evolution-manager
        fi

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.110.0'
        extended: true

    - name: configure aws tools creds
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.GITHUB_ACTIONS_PUBLISHING_ROLE }}
        role-session-name: ${{ github.event.repository.name }}
        aws-region: ${{ secrets.GITHUB_ACTIONS_PUBLISHING_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.WRITE_TOKEN }}

    - name: bootstrap
      shell: bash
      run: |
        cp .npmrc $HOME/.npmrc
        npm ci
        npx lerna bootstrap --since --ci --include-dependencies
        npx lerna run build --since --include-dependencies
      env:
        NPM_TOKEN: ${{ secrets.READ_TOKEN }}
        JAVA_OPTS: "-Xms256m -Xmx1024m"

    # Need at at least a file in there as download action will fail if no artifact found
    # upload does not upload empty folders
    - name: create github actions upload folder
      shell: bash
      run: |
        mkdir ci-upload
        echo "Upload your artifacts to this location for debugging or sharing accross jobs" > ci-upload/README.md
      
    - name: test:integration
      if: github.ref != 'refs/heads/main' && inputs.run-integration-tests == 'true'
      shell: bash
      run: |
        bash ${{ github.action_path }}/integrationTest.sh
      env:
        NPM_TOKEN: ${{ secrets.READ_TOKEN }}
        DYNAMO_DB_TABLE: ${{ env.AWS_DYNAMO_DB_TABLE }}
        AWS_ACCESS_KEY_ID: ${{ env.AWS_DYNAMO_DB_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ env.AWS_DYNAMO_DB_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ env.AWS_DYNAMO_DB_REGION }}
        AWS_ENDPOINT: ${{ env.AWS_DYNAMO_DB_ENDPOINT }}
        EVENT_SOURCE: Memory
        SCHEDULER_SOURCE: Memory

    - name: test:prepublish:init
      if: github.ref != 'refs/heads/main'
      shell: bash
      run: |
        if [ -x scripts/prepublish-init.sh ]
        then
          bash scripts/prepublish-init.sh
        fi
      env:
        NPM_TOKEN: ${{ secrets.READ_TOKEN }}

    - name: test:prepublish
      if: github.ref != 'refs/heads/main'
      shell: bash
      run: |
        if npm run | grep -q "nx:prepublish"; then
          npm i -g @auditmation/platform-dataloader@latest
          npm run nx:prepublish
        fi
      env:
        NPM_TOKEN: ${{ secrets.READ_TOKEN }}
        DYNAMO_DB_TABLE: ${{ env.AWS_DYNAMO_DB_TABLE }}
        AWS_ACCESS_KEY_ID: ${{ env.AWS_DYNAMO_DB_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ env.AWS_DYNAMO_DB_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ env.AWS_DYNAMO_DB_REGION }}
        AWS_ENDPOINT: ${{ env.AWS_DYNAMO_DB_ENDPOINT }}
        EVENT_SOURCE: Memory
        SCHEDULER_SOURCE: Memory

    - name: test:postpublish
      if: github.ref != 'refs/heads/main'
      shell: bash
      run: |
        if [ -x scripts/postpublish.sh ]
        then
          bash scripts/postpublish.sh --dry-run
        fi
      env:
        NPM_TOKEN: ${{ secrets.READ_TOKEN }}
        UPLOAD_FOLDER_NAME: ci-upload

    - name: Upload test artifacts
      if: github.ref != 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: ci-upload
        path: ci-upload/
        if-no-files-found: warn
        retention-days: 1

    - name: Slack Notification
      uses: rtCamp/action-slack-notify@master
      if: failure()
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_DEVOPS_NOTIFICATIONS }} 
        SLACK_ICON_EMOJI: ":fire"
        MSG_MINIMAL: 'true'
        SLACK_TITLE: ":fire: ${{ github.repository }} pr test failed"
        SLACK_MESSAGE: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        SLACK_COLOR: danger
